spring:
  datasource:
    url: jdbc:postgresql://db:5433/course
    username: postgres
    password: 10172003
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect